name: CD for java calculator

on:
  workflow_run:
    workflows: ["CI for Java Calculator"]
    types:
      - completed

jobs:
  staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Build package 
        run: mvn clean package -DskipTests

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: target/*.jar

      - name: Deploy to staging
        run: |
          echo "Deploying to Staging"
          ls target/

  production: 
    needs: staging
    runs-on : ubuntu-latest
    environment: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./site

      - name: Deploy to production
        run: |
          echo "Deploying to Production"
          ls -l ./site
      
